<div id="el">

    <div v-if="Game.round == null" class="panel panel-default">
        <div class="panel-heading">
            Trick Or Treat - Sign in
        </div>
        <div class="panel-body">
            <input type="text" name="player_1" id="player_1" value="" v-model="Players.player_1"/><br/>
            <input type="text" name="player_2" id="player_2" value="" v-model="Players.player_2"/><br/>
            <input class="btn btn-default" type="button" name="SignIn" value="We're crazy hungry, Sign in!" v-on:click="signIn">
        </div>
    </div>
    <div v-else>
        <div v-if="Game.state==1">
            <h1>{{Players.player_1}} pick your ingredients for your friend {{Players.player_2}}</h1>
            <p>Todo: List of ingredients</p>
            <input class="btn btn-default" type="button" name="confirmIngredientsPlayer1" value="Confirm ingredients for my friend {{Players.player_2}}" v-on:click="confirmIngredients">
        </div>
    </div>

    <div v-if="Game.state==2">
        <h1>{{Players.player_1}} did you eat your meal?</h1>
        <input class="btn btn-default" type="button" name="playerHasFinishedDish1" value="Yes" v-on:click="playerHasFinishedDish(1)"><br/>
        <input class="btn btn-default" type="button" name="playerHasDidNotFinishDish1" value="No way!" v-on:click="playerHasDidNotFinishDish(1)">

        <h1>{{Players.player_2}} did you eat your meal?</h1>
        <input class="btn btn-default" type="button" name="playerHasFinishedDish2" value="Yes" v-on:click="playerHasFinishedDish(2)"><br/>
        <input class="btn btn-default" type="button" name="playerHasDidNotFinishDish2" value="No way!" v-on:click="playerHasDidNotFinishDish(2)">

    </div>
</div>