<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trick or Treat</title>

    <link rel="stylesheet" href="/assets/css/style.css">
<style>
    body {
    color: white;
    }
</style>
</head>
<body>

<div class="neutral-background"></div>
<div id="el">
    <section class="topbar">

        <div class="l-container">

            <div class="logo">
                <img src="/assets/img/trickortreat_logo.png" alt="">
            </div>

            <div class="round-notation">
                Round #{{ roundNo }}
            </div>

        </div>
    </section>

    <section class="player-names" v-show="gameState == 'signIn'">
        <div class="l-container">
            <input type="text" placeholder="Player one" v-model="Players.PlayerOne.name">
            <input type="text" placeholder="Player two" v-model="Players.PlayerTwo.name">
            <button name="submit" v-on:click="initialiseGame">Play</button>
        </div>
    </section>

    <section class="l-container" v-show="gameState == 'passToPlayer'">
        {{ gameCurrentPlayer.name }} may choose the ingredients
        <button name="submit" v-on:click="chooseIngredients">Go</button>
    </section>

    <div v-show="gameState == 'chooseIngredients'">
        <section class="l-container">
            {{ gameCurrentPlayer.name }}, choose your ingredients
            <ul>
                <li v-for="item in availableIngredients">
                    <label>
                    <input type="checkbox" v-bind:value="item.id" v-model="gameCurrentPlayer.chosenIngredients"/> {{ item.name }}
                    <span></span>
                    </label>
                </li>
            </ul>
            <button name="submit" v-on:click="confirmIngredients">Confirm</button>
        </section>
    </div>

    <section class="l-container" v-show="gameState == 'confirmRoundResult'">
        <label>
            <input type="checkbox"
                   v-model="roundResult.playerOneResult"
            />{{ Players.PlayerOne.name }}
            <span></span>
        </label>
        <br/>
        <label>
            <input type="checkbox"
                   v-model="roundResult.playerTwoResult"
                    v-bind:true-value="true"
                    v-bind:false-value="false"
            />
            {{ Players.PlayerTwo.name }}
            <span></span>
        </label>

        <button name="submit" v-on:click="finishRound">Finish Round</button>
    </section>

    <section class="l-container" v-show="gameState == 'congratulateWinner'">
        <label>
            <input type="checkbox" v-model="Players.PlayerOne.isGameOver"/>
            <span>{{ Players.PlayerOne.name }} </span>
        </label>
        <button href="/play" name="submit">New game, still hungry!</button>
    </section>

</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/vue/1.0.26/vue.js"></script>
<script src="https://cdn.jsdelivr.net/vue.resource/0.9.3/vue-resource.min.js"></script>
<script src="/assets/js/main.js"></script>
</body>
</html>