<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trick or Treat</title>

    <link rel="stylesheet" href="/assets/css/style.css">
<style>
    body {
    color: white;
    }
</style>
</head>
<body>

<div class="neutral-background"></div>
<div id="el">
    <section class="topbar">

        <div class="l-container">

            <div class="logo">
                <img src="/assets/img/trickortreat_logo.png" alt="">
            </div>

            <div class="round-notation">
                Round #{{ roundNumber }}
            </div>

        </div>
    </section>

    <section class="player-names" v-show="gameState == 'signIn'">
        <div class="l-container">
            <input type="text" placeholder="Player one" v-model="Players.PlayerOne.name">
            <input type="text" placeholder="Player two" v-model="Players.PlayerTwo.name">
            <button name="submit" v-on:click="initialiseGame">Play</button>
        </div>
    </section>

    <section class="l-container" v-show="gameState == 'passToPlayer'">
        <div class="instruction-container">
            {{ gameCurrentPlayer.name }} may choose the ingredients
        </div>
        <button name="submit" v-on:click="chooseIngredients">Go</button>
    </section>

    <div v-show="gameState == 'chooseIngredients'">
        <section class="l-container">
            <div class="instruction-container">
                {{ gameCurrentPlayer.name }}, choose your ingredients
            </div>
            <ul>
                <li class="ingredients-list" v-for="item in availableIngredients">
                    <label>
                    <input type="checkbox" v-bind:value="item.id" v-model="gameCurrentPlayer.chosenIngredients" />
                        <span>{{ item.name }}</span>
                        <!-- <img src="http://placekitten.com/100/100" />-->
                    </label>
                </li>
            </ul>
            <button name="submit" v-on:click="confirmIngredients">Confirm</button>
        </section>
    </div>

    <section class="l-container" v-show="gameState == 'confirmRoundResult'">
        <div class="instruction-container">
        <label>
            <input type="checkbox"
                   v-model="roundResult.playerOneResult"
            />{{ Players.PlayerOne.name }}
            <span></span>
        </label>
        <br/>
        <label>
            <input type="checkbox"
                   v-model="roundResult.playerTwoResult"
                    v-bind:true-value="true"
                    v-bind:false-value="false"
            />
            {{ Players.PlayerTwo.name }}
            <span></span>
        </label>

        <button name="submit" v-on:click="finishRound">Finish Round</button>
        </div>
    </section>

    <section class="l-container" v-show="gameState == 'congratulateWinner'">

            <div class="instruction-container">Congratulations {{ winner }} </div>
            <button href="/play" v-on:click="newGame">New game, still hungry!</button>
    </section>

    <section class="l-container" v-show="gameState == 'draw'">
        <div class="instruction-container">Both not hungry?</div>
        <button href="/play"  v-on:click="newGame">New game, still hungry!</button>
    </section>

</div>
<script type="text/javascript" src="/assets/js/jquery.min.js"></script>
<script type="text/javascript" src="/assets/js/vue.js"></script>
<script type="text/javascript" src="/assets/js/vue-resource.min.js"></script>
<script type="text/javascript" src="/assets/js/main.js"></script>
</body>
</html>